# welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Adolfo Builes"
email: builes.adolfo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write about technology, being a human and books.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://blog.abuiles.com
twitter_username: abuiles
github_username:  abuiles

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - octopress-social
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /blog/:year/:month/:day/:title/
google_analytics: UA-32360357-1
disqus:
  shortname: abuiles

plugins:
  - directory_tag

collections:
  reading_feed:
    output: true
    permalink: /reading-feed/:name
    path: "reading_feed"
  motorcycling:
    output: true
    permalink: /viajes/:name

defaults:
  - scope:
      type: reading_feed
    values:
      layout: book

header_pages:
  - articles.md
  - reading-feed.md

twitter:
  username: abuiles                         # Add your Twitter handle
  tweet_count:         false              # Show number of shares on Twitter
  size:                large             # Or large
  tweet_message:       ":title by :username :hashtags - :url" # With Tweet button Twitter add the URL last
  tweet_link_text:     Twitter            # Configure the link text
  tweet_link_title:    Share on Twitter   # Share link title
  profile_link_text:   Follow :username
  profile_link_title:  Follow :username on Twitter  # Profile link title text
