title: "Adolfo Builes"
email:
description: > # this means to ignore newlines until "baseurl:"
  I write about technology, humanity, and books.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://blog.abuiles.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - octopress-social
  # - directory_tag
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /blog/:year/:month/:day/:title/
google_analytics: UA-32360357-1

# plugins:
#   - directory_tag

collections:
  ai_at_work:
    output: false
  reading_feed:
    output: true
    permalink: /reading-feed/:name
    path: "reading_feed"
  motorcycling:
    output: true
    permalink: /viajes/:name
  notes:
    output: true
    permalink: /notes/:name

defaults:
  - scope:
      type: reading_feed
    values:
      layout: book

header_pages:
  - about.md
  - articles.md

twitter:
  username: abuiles                         # Add your Twitter handle
  tweet_count:         false              # Show number of shares on Twitter
  size:                large             # Or large
  tweet_message:       ":title by :username :hashtags - :url" # With Tweet button Twitter add the URL last
  tweet_link_text:     Twitter            # Configure the link text
  tweet_link_title:    Share on Twitter   # Share link title
  profile_link_text:   Follow :username
  profile_link_title:  Follow :username on Twitter  # Profile link title text
